# project_root/docker-compose.jenkins.yml
# version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    privileged: true
    user: root
    ports:
      - "8083:8080"
      - "50001:50000"  # Jenkins slave port # 로컬에서 포트 충돌로 인해 변경
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo_cache:/usr/local/cargo/registry
      - flutter_cache:/root/.pub-cache  # Flutter 캐시 추가
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RUST_VERSION=1.82
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - flick_network

# 네트워크와 볼륨은 기존 rust_server/docker-compose.yml과 공유
networks:
  flick_network:
    external: true
    name: flick_network

volumes:
  jenkins_home:
  cargo_cache:
    external: true
  flutter_cache: