version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: flickdb
      POSTGRES_USER: flickuser
<<<<<<< HEAD
      POSTGRES_PASSWORD: flickpass # 실제 운영환경에서는 보안 강화 필요
=======
      POSTGRES_PASSWORD: flickpass
>>>>>>> d18e561ecf6f553bddd2ea81a6fbdc848ce1417d
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flickuser -d flickdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rust_server:
    build:
      context: ../rust_server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../rust_server:/usr/src/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/usr/src/app/target
    environment:
      DATABASE_URL: "postgres://flickuser:flickpass@timescaledb:5432/flickdb"
      RUST_LOG: "debug"
      RUST_BACKTRACE: 1
      JWT_SECRET: "your-development-secret-key"
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
<<<<<<< HEAD
  timescaledb_data: # Database 데이터 저장
  cargo_cache: # Rust 빌드 캐시
  target_cache: # Rust 컴파일 결과물 캐시
=======
  timescaledb_data:
  cargo_cache:
  target_cache:
>>>>>>> d18e561ecf6f553bddd2ea81a6fbdc848ce1417d
