name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Rust tests
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Run Rust tests
      working-directory: ./rust_server
      run: cargo test

    # Flutter tests
    - name: Install Flutter
      uses: subosito/flutter-action@v2
    
    - name: Get Flutter dependencies
      working-directory: ./flutter_client
      run: flutter pub get
    
    - name: Run Flutter tests
      working-directory: ./flutter_client
      run: flutter test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker images
      run: docker-compose build

    # Local build verification
    - name: Verify build
      run: echo "Build completed successfully!"
